In [ ]:
from scipy import stats
import pandas as pd
import numpy as np


In [ ]:
glaxo_df=pd.read_csv('glaxo_df.csv',index_col=0)
glaxo_df.head()

Date.1    Close      gain
Date                                     
2010-01-05  2010-01-05  1616.80 -0.005444
2010-01-06  2010-01-06  1638.50  0.013422
2010-01-07  2010-01-07  1648.70  0.006225
2010-01-08  2010-01-08  1639.80 -0.005398
2010-01-11  2010-01-11  1629.45 -0.006312

In [ ]:
glaxo_df.shape

(1738, 3)

In [ ]:
glaxo_df_ci = stats.norm.interval(0.95,
loc = glaxo_df.gain.mean(),
scale = glaxo_df.gain.std()/(np.sqrt(1738)))
print( 'Gain at 95% confidence interval is:', np.round(glaxo_df_ci, 4))

Gain at 95% confidence interval is: [-0.0002  0.001 ]


In [ ]:
beml_df=pd.read_csv('beml_df.csv')

beml_df_ci = stats.norm.interval(0.95,
loc=beml_df.gain.mean(),
scale=beml_df.gain.std()/(np.sqrt(1738)))

In [ ]:
np.round(beml_df_ci,4)

array([-0.001 ,  0.0015])

In [ ]:
t_intervals=stats.t.interval(0.95,1737,glaxo_df.gain.mean(),glaxo_df.gain.std()/np.sqrt(1738))
np.round(t_intervals,4)

array([-0.0002,  0.001 ])

In [ ]:
t_intervals=stats.t.interval(0.95,1737,beml_df.gain.mean(),beml_df.gain.std()/np.sqrt(1738))
np.round(t_intervals,4)

array([-0.001 ,  0.0015])

In [ ]:
#@##t confidence interval


stats.t.interval(0.95,139,1990,239.4) #(confidence level(1-a),degrees of freedom, sample mean(xbar),error(sample sd/sqrt(n)))

In [ ]:
stats.t.ppf(0.975,139)

In [ ]:
from scipy import stats
stats.norm.interval(0.95,1990,211.29) #(confidence level(1-a),sample mean(xbar),error(sd/sqrt(n)))

In [ ]:
stats.norm.interval(0.90,1990,211.29)

(1642.4588771614233, 2337.5411228385765)

In [ ]:
stats.norm.ppf(.95)

1.6448536269514722

In [ ]:
from scipy import stats

In [ ]:
stats.norm.interval(0.95,1990,211.29)  ### (Confidence level,Point estimator,sigma/sqrt(n))

In [ ]:
stats.norm.ppf(0.975)

In [ ]:
from scipy import stats
#import scipy.stats as ss
import numpy as np

In [ ]:
stats.norm.interval(0.95,1990,(2500/np.sqrt(140)))   #confidence level, point estimator, standard error(sigma/root(n))

(1575.8820248378292, 2404.1179751621708)

In [ ]:
import numpy as np
np.sqrt(144)

12.0

In [ ]:
from scipy import stats
stats.norm.interval(0.95,1990,(2500/np.sqrt(140)))

(1575.8820248378292, 2404.1179751621708)

In [ ]:
stats.norm.ppf(0.975)

1.959963984540054

In [ ]:
import numpy as np
from scipy import stats
stats.t.interval(0.95,139,1990,(2833/np.sqrt(140)))

(1516.5999869168315, 2463.4000130831682)

In [ ]:
stats.t.ppf(0.975,139)

1.977177724476122

In [ ]:
import numpy as np
np.sqrt(4)

np.float64(2.0)

In [ ]:
from scipy import stats

stats.norm.interval(0.95,1990,(2500/np.sqrt(140)))

(np.float64(1575.8820248378292), np.float64(2404.1179751621708))

In [ ]:
stats.t.interval(0.95,139,1990,2833/np.sqrt(140))

(np.float64(1516.5999869168315), np.float64(2463.4000130831682))

In [ ]:
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [ ]:
#Z at 0.92
stats.norm.ppf(0.96)

np.float64(1.7506860712521692)

In [ ]:

# t critical at 0.95
stats.t.ppf(0.975,139)

np.float64(1.977177724476122)

In [ ]:
stats.t.ppf(0.95,139)

np.float64(1.6558898677725957)

In [ ]:
from scipy import stats
import numpy as np

In [ ]:
np.sqrt(1440)

np.float64(37.94733192202055)

In [ ]:
stats.norm.interval(0.95,loc=1990,scale=2500/np.sqrt(140))

(np.float64(1575.8820248378292), np.float64(2404.1179751621708))

In [ ]:
stats.norm.ppf(1-(0.05/2))

np.float64(1.959963984540054)

In [ ]:
stats.t.interval(0.95,139,1990,2833/np.sqrt(140))    #confidence level,degrees of freedom,point estimator, standard error(s/sqrt(n))

(np.float64(1516.5999869168315), np.float64(2463.4000130831682))

In [ ]:
round(stats.t.ppf((1-0.05/2),139),4)

np.float64(1.9772)

In [ ]:
from scipy import stats
import numpy as np
cl=0.95
n=140
pe=1990
s=2833
stats.t.interval(cl,n-1,pe,s/np.sqrt(n))
#confidence level,degree of freedom,point estimator,standard error( s/root(n))

(np.float64(1516.5999869168315), np.float64(2463.4000130831682))

In [ ]:
stats.t.ppf(1-0.05/2,139)   #(1-alpha/2,degree of freedom)

np.float64(1.977177724476122)

In [1]:
#Random Number generation

In [2]:
#discrete uniform random numbers

import numpy as np

In [3]:
np.random.randint(0,5,size=100)

array([1, 3, 2, 3, 0, 0, 4, 2, 2, 1, 0, 4, 3, 4, 2, 2, 1, 0, 3, 3, 2, 1,
       1, 2, 1, 0, 1, 0, 3, 0, 4, 2, 0, 0, 0, 3, 4, 1, 4, 3, 1, 4, 3, 2,
       4, 3, 1, 2, 0, 0, 2, 2, 3, 1, 4, 0, 0, 4, 3, 4, 3, 2, 2, 0, 2, 1,
       4, 3, 1, 2, 3, 2, 0, 0, 3, 1, 4, 4, 4, 1, 1, 3, 1, 1, 3, 1, 4, 3,
       3, 4, 1, 2, 3, 3, 1, 4, 3, 3, 1, 3])

In [4]:
#continuous uniform(rectangular) random samples
np.random.uniform(0,5,100)

array([3.33516392, 0.85198686, 4.2353265 , 4.17959392, 1.45571183,
       4.23541394, 2.87630261, 3.92254465, 3.58814493, 3.27242921,
       3.88928351, 1.33137986, 1.33141662, 0.80317463, 0.48273167,
       4.90689291, 2.01355992, 1.95074979, 1.46397593, 2.82098957,
       2.73998929, 1.5358595 , 3.78643804, 2.14835637, 4.70129527,
       0.87971241, 0.4352728 , 3.34570121, 4.8481289 , 0.93218873,
       1.84916808, 1.1286803 , 3.0518456 , 3.59391306, 0.99622421,
       4.49062756, 0.11167831, 2.53278686, 4.6029794 , 0.17348865,
       3.08485027, 0.85720632, 0.26895546, 1.42946549, 4.06548222,
       0.96017785, 4.46181592, 4.04050029, 3.47434682, 3.56401366,
       3.74475134, 0.89427657, 2.42039828, 3.10810302, 1.90698982,
       3.16366154, 0.89630095, 2.67691401, 1.5749655 , 4.11514598,
       2.7881932 , 4.75904556, 4.38546429, 3.86233394, 3.62371358,
       2.00148793, 0.11118475, 4.66619006, 0.04705841, 2.97373191,
       3.96794101, 4.13082095, 3.78512395, 0.20537939, 0.19093

In [8]:
np.random.binomial(1,0.75,100)    #success value,prob of success,size of samples

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1])

In [14]:
#normal random sample(mean,std)

np.round(np.random.normal(5,3,100))

array([ 4.,  4.,  3.,  5.,  0.,  1.,  5.,  2.,  4.,  4.,  3.,  4.,  4.,
        5.,  6., -2.,  1.,  5.,  1.,  5.,  5., -1.,  6.,  2., 10.,  6.,
        5.,  3.,  2.,  5.,  6.,  6.,  6.,  9., 11.,  4.,  7.,  1.,  8.,
        6.,  8., 11.,  3.,  6.,  9.,  4.,  4.,  4., -0.,  9.,  8.,  4.,
        4.,  2.,  1.,  4.,  5.,  5.,  5.,  3.,  7.,  5.,  4.,  6.,  9.,
       10.,  3.,  4., 12.,  1.,  3.,  1.,  6.,  8.,  1., -1.,  6.,  5.,
        4.,  3.,  5.,  1.,  3.,  6.,  3.,  4.,  8.,  8., -1.,  7.,  3.,
        6.,  2.,  4.,  6., 11.,  2., 10.,  8.,  7.])

In [15]:
np.random.normal(0,1,100)

array([ 0.20417688,  1.09334598, -0.14613569, -0.32425063, -0.16834804,
       -0.58877719,  2.01738645,  2.07282233,  0.07270866,  2.25890394,
       -0.85572423,  0.89164148,  1.3998594 , -1.59358236, -0.660984  ,
       -1.52106102,  0.34835608,  0.73007332,  1.26601131,  0.10271703,
       -0.86402859,  0.47890084, -0.55722398, -1.12445832,  0.30793331,
        0.47491714,  1.05950241, -2.2384593 , -2.75349285,  0.14666938,
        1.42666486,  1.15018405, -0.97579354,  0.85132056,  0.99257927,
       -0.50118172, -0.55848791,  0.72753638,  0.82443442,  1.7433305 ,
        0.73323066, -0.13395499,  0.40694011,  0.66586757, -0.48951964,
       -0.36480286,  1.1748578 ,  0.43891662,  0.1012448 ,  1.40724632,
       -2.80624264,  0.11039207,  1.93955162,  0.04178377,  1.55708634,
       -0.73800011, -0.06147298, -0.46324101,  0.5225345 ,  1.11484522,
       -0.75355281,  0.94257005,  1.5382405 , -1.69197788,  1.13015079,
       -1.74633649,  0.11245388, -0.53979078,  0.5288369 , -0.03

In [17]:
import pandas as pd
data=pd.DataFrame({
    "uniform":np.random.uniform(0,1,100),
    "normal":np.random.normal(0,1,100)
              })

In [18]:
data

uniform    normal
0   0.609189 -0.205286
1   0.590025 -0.602987
2   0.228133 -0.143563
3   0.745983 -0.508089
4   0.045729  0.473128
..       ...       ...
95  0.236088 -0.683800
96  0.442304 -1.214913
97  0.167494  0.775079
98  0.682912 -0.323856
99  0.904223  1.310611

[100 rows x 2 columns]

In [19]:
data

uniform    normal
0   0.609189 -0.205286
1   0.590025 -0.602987
2   0.228133 -0.143563
3   0.745983 -0.508089
4   0.045729  0.473128
..       ...       ...
95  0.236088 -0.683800
96  0.442304 -1.214913
97  0.167494  0.775079
98  0.682912 -0.323856
99  0.904223  1.310611

[100 rows x 2 columns]

In [20]:
data.sample(10)

uniform    normal
30  0.043187 -0.666999
50  0.137476 -0.624678
67  0.837222 -0.446386
60  0.183999  1.176156
73  0.600781 -1.659270
14  0.089916  0.740259
49  0.612072  0.074404
3   0.745983 -0.508089
92  0.525697 -0.263273
47  0.733462  0.149038