In [ ]:
#import the libraries
import pandas as pd
import scipy
import numpy as np
from scipy import stats

# Super Market example

In [ ]:
import numpy as np
t=(130-120)/(40/(np.sqrt(80)))
t

np.float64(2.23606797749979)

In [ ]:
from scipy import stats
stats.t.ppf(0.975,79)

np.float64(1.9904502102301282)

In [ ]:
#Conclusion:
#since tcal > tcrit , We reject null hyp, i.e., accept alt hypotheis.
#Hence it is evident that on an average the customers are spending more than $120 per week

In [ ]:
stats.t.ppf(0.975,79)

np.float64(1.9904502102301282)

# Call Center example

In [ ]:
import numpy as np
(4.6-4)/(3/np.sqrt(50))

np.float64(1.4142135623730943)

In [ ]:
from scipy import stats
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [ ]:
2*stats.norm.cdf(-3.5)

np.float64(0.00046525815807105003)

# One tail test

In [ ]:
import pandas as pd
data=pd.Series([0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418])

In [ ]:
stats.ttest_1samp(data,0.3)

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [ ]:
#This gives two tail test p value so divide by 2 to get final p-value
from scipy import stats
p=stats.ttest_1samp(data,0.3)[1]
p_value= p/2
p_value

np.float64(0.029265164842448826)

In [ ]:
data2=pd.Series([70,84,96,63,50,89,92,65,70,80])
stats.ttest_1samp(data2,80)

TtestResult(statistic=np.float64(-0.8824292337730089), pvalue=np.float64(0.4004992968146376), df=np.int64(9))

In [ ]:
p=stats.ttest_1samp(data2,80)[1]
p/2

np.float64(0.2002496484073188)

# Two Tail test

In [ ]:
import pandas as pd
Control=pd.Series([91, 87, 99, 77, 88, 91])
Treat =pd.Series([101, 110, 103, 93, 99, 104])


In [ ]:
import scipy.stats as stats
stats.ttest_ind(Control,Treat)

TtestResult(statistic=np.float64(-3.4456126735364876), pvalue=np.float64(0.006272124350809803), df=np.float64(10.0))

In [ ]:
stats.t.ppf(0.975,10)

np.float64(2.2281388519649385)

# 2 Proportion Test

In [ ]:
import numpy as np

In [ ]:
#Data:

n1 = 247
p1 = 0.37

n2 = 308
p2 = 0.39

In [ ]:
population1 = np.random.binomial(1, p1, n1)
population2 = np.random.binomial(1, p2, n2)

In [ ]:
population1

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1])

In [ ]:
population2

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,

In [ ]:
from scipy import stats
stats.ttest_ind(population1, population2)

TtestResult(statistic=np.float64(-1.1080424303213392), pvalue=np.float64(0.26832518146607814), df=np.float64(553.0))

In [ ]:
np.random.randint(100,10000,100)

array([6731, 9960, 9224, 8159, 8911, 6903, 6623, 6499, 6287, 5312, 9927,
       7558, 3881, 8234, 4973, 6689, 3536, 4035, 8807,  930, 5024, 3304,
       8165, 6503, 4061, 7815, 1103, 8248,  628, 8934, 5553, 1690, 1137,
       4163, 7478, 5067, 6670, 2095, 4876, 8511, 1600,  444, 9138, 1293,
       7481, 8375,  184, 6117, 3316, 3949, 3077, 1720, 9786, 4403, 8930,
       5723, 4252, 6213, 6939, 5790, 7424, 4263,  236, 2995, 1304, 7487,
       1876, 8618, 6392, 2112, 2536, 4809, 8176, 1395,  138, 9302, 1499,
        470, 9575, 4917, 5774, 1018, 1936, 9868, 4665, 8014, 5239, 3160,
       1097, 2093, 5685, 9967, 2281,  669, 8762, 4700, 6826, 7018, 6246,
       1811])

In [ ]:
np.random.uniform(0,1,100)

array([0.56454299, 0.95457842, 0.21096529, 0.90789541, 0.25373929,
       0.67633826, 0.76024756, 0.25789966, 0.52567555, 0.32449682,
       0.49930374, 0.31271363, 0.52733942, 0.80940271, 0.91959735,
       0.20104033, 0.07478337, 0.41657315, 0.7085963 , 0.16512628,
       0.28496635, 0.26024704, 0.89229333, 0.85880226, 0.44120229,
       0.33397316, 0.03497209, 0.62725455, 0.6005068 , 0.96949473,
       0.06064825, 0.12725649, 0.39061585, 0.21705537, 0.13997118,
       0.78858332, 0.83282101, 0.09128827, 0.0089064 , 0.63950163,
       0.36383702, 0.03597582, 0.19551752, 0.50228277, 0.87320246,
       0.3145371 , 0.50793291, 0.66344415, 0.49539953, 0.33062583,
       0.62624205, 0.12646676, 0.36324582, 0.07204873, 0.84322592,
       0.06502601, 0.74322341, 0.45909407, 0.26037586, 0.31706201,
       0.56569027, 0.42849488, 0.10053067, 0.8731953 , 0.10352184,
       0.76793189, 0.69122526, 0.44567527, 0.90014302, 0.30175176,
       0.84404044, 0.08970023, 0.84646316, 0.77247724, 0.93499

In [ ]:
np.random.normal(5,25,100)   #5 mean,25sd,100 samples

array([-1.36578531e+01, -2.36984470e+01, -1.83152150e+01, -5.89406840e-02,
       -2.92515735e+01, -1.55343375e+01, -6.16763764e+00, -1.22611396e+00,
       -9.55964837e-01, -5.51041695e+00, -2.31891340e+00, -3.20922068e+01,
        1.27071281e+01,  1.45953284e+01, -5.56691738e+00,  1.75615747e+01,
        2.55058884e+01,  3.40203512e+01,  3.53041320e+01, -1.71175047e+01,
        2.15436534e+01,  3.01189773e+01,  3.19297577e+01,  6.86921320e+00,
       -4.92595764e+01,  1.03326060e+01, -2.73955134e+01, -1.03130322e+01,
       -1.88193685e+01, -2.76822775e+00, -2.78950928e+00, -1.10014771e+01,
        5.91325403e+00,  2.88302947e+01, -3.56626239e+00, -2.94827410e+01,
        1.34282901e+01,  2.01262237e+01, -2.54445824e+01,  3.77104755e+01,
       -6.93387038e+00,  4.45380763e+00, -8.35960887e+00,  9.94906162e+00,
        3.87268930e+01,  2.81347025e+01,  4.41305630e+01,  1.63724793e+00,
        2.75019950e+01,  1.63829586e+01,  3.82063921e+01, -2.52705692e+01,
       -2.46452763e+01, -

In [ ]:
import numpy as np

z=(130-120)/(40/np.sqrt(80))

In [ ]:
z

np.float64(2.23606797749979)

In [ ]:
from scipy import stats
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [ ]:
stats.t.ppf(0.975,79)

np.float64(1.9904502102301282)

In [ ]:
z=(4.1-4)/(3/np.sqrt(50))
z

np.float64(0.235702260395515)

In [ ]:
stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [ ]:
lst=[0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418]

In [ ]:
import pandas as pd
df=pd.Series(lst)
df

0    0.593
1    0.142
2    0.329
3    0.691
4    0.231
5    0.793
6    0.519
7    0.392
8    0.418
dtype: float64

In [ ]:
stats.ttest_1samp(df,0.3)

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [ ]:
stats.ttest_1samp(df,0.3)[1]/2


np.float64(0.029265164842448826)

In [ ]:
va=[]


In [ ]:
n1=247
p1=0.37


In [ ]:
import numpy as np
popA=np.random.binomial(1,p1,n1)
popA

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1])

In [ ]:
n2=308
p2=0.39
popB=np.random.binomial(1,p2,n2)
popB

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,

In [ ]:
stats.ttest_ind(popA,popB)

TtestResult(statistic=np.float64(0.5710316355745881), pvalue=np.float64(0.5682101765417185), df=np.float64(553.0))

In [ ]:
np.random.randint(1,100,100)

array([67,  2, 18, 94, 21,  6, 50, 38, 43, 93, 95, 62, 12, 31, 62, 14, 47,
       34, 69, 82, 93,  5, 38, 92, 65, 86,  7,  2, 99, 43, 25, 66, 28, 31,
       25, 72, 27, 62, 89, 79, 78, 22, 20, 16, 46, 65, 30, 44, 55, 55, 23,
       80, 68,  6, 48, 58, 75, 27, 71, 57, 28, 82, 70, 12, 52, 82, 72, 92,
       99, 95, 34, 24, 97, 65, 82, 70, 77, 49,  4, 27, 57, 86,  6, 69, 40,
       99, 20, 75, 68, 29,  4, 65, 89, 37, 37, 51, 61,  9, 42, 80])

In [ ]:
np.random.uniform(0,1,100)

array([0.15392417, 0.23295282, 0.66117622, 0.63635275, 0.89916081,
       0.28673088, 0.46148706, 0.45558405, 0.55309459, 0.31849468,
       0.71366251, 0.58963178, 0.65265848, 0.66368375, 0.70211068,
       0.69146772, 0.79032917, 0.40292254, 0.83607993, 0.44474384,
       0.4227162 , 0.72822101, 0.41192131, 0.21942565, 0.17852562,
       0.62023142, 0.08356408, 0.01405033, 0.07136384, 0.48211   ,
       0.1198117 , 0.36945959, 0.33895172, 0.0289873 , 0.33586612,
       0.54604838, 0.69436481, 0.07346921, 0.95473344, 0.48546358,
       0.68367107, 0.78548083, 0.63085157, 0.95807307, 0.72550405,
       0.74998454, 0.41556905, 0.44724969, 0.65645028, 0.47699711,
       0.25763154, 0.54695536, 0.42465746, 0.70065394, 0.20843651,
       0.28489417, 0.73034829, 0.49864769, 0.73974775, 0.69662061,
       0.47076448, 0.22065946, 0.5518451 , 0.33755835, 0.46873087,
       0.64866118, 0.97764833, 0.18282258, 0.18277136, 0.13477773,
       0.02117465, 0.71388296, 0.78037714, 0.3089629 , 0.75635

In [ ]:
np.random.normal(30,25,100)

array([ 4.65477305e+01,  4.58931335e+01,  6.55833029e+01,  4.70673695e+01,
        1.89066393e+01,  4.43053628e+01,  8.96991121e+01,  8.80189132e-02,
        1.65997157e+01,  6.38345116e+01,  2.33051198e+01,  6.63843919e+01,
        1.45052926e+01,  2.36732822e+01,  3.99046677e+01,  3.37244687e+01,
        2.40752068e+01,  7.25700158e+00,  3.73423922e+01,  5.24723348e+01,
       -9.42938376e+00,  7.47354897e+01,  3.00188341e+01,  5.57668004e+01,
       -3.46942758e+00,  5.57333037e+01,  6.72520804e+01,  1.69159145e+01,
        5.38951961e+01,  1.23673752e+01,  9.69104625e+00,  9.12682596e+01,
        5.91583245e+01,  2.11976184e+01,  3.78941824e+01,  1.40513470e+01,
        1.18322065e+02,  2.46512697e+01,  3.45391368e+01, -1.96272330e+01,
        4.96506108e+01, -8.67957539e+00,  3.60737485e+01, -1.11367679e+01,
        2.06444173e+01, -1.28214338e+01,  4.59744499e+01,  1.75601886e+01,
        3.18575975e+01, -1.72093733e+01,  3.06089978e+01,  2.09488647e+01,
        5.85983457e+01,  

In [1]:
from scipy import stats
import numpy as np

In [3]:
#H0:mu<=120, Donot launch loyalty program
#H1:mu>120, Launch loyalty program

#test: t-test

#sample study
alpha= 0.05
n=80
x_bar=130
s=40
mu=120

#t-calculation
t_cal=(x_bar-mu)/(s/np.sqrt(n))
t_cal

np.float64(2.23606797749979)

In [4]:
t_crit=stats.t.ppf(1-(alpha/2),n-1)

In [ ]:
#Conclusion: since t_cal>t_crit, we reject HO
#i.e., on an average the customers are spending more than 120$ per week, hence the shopkeeper
#may launch the loyalty program

if t_cal<=t_crit:
  print("Accept Null Hypothesis, i.e, on an average the customers are spending less than 120$ per week, hence the shopkeeper must not launch the loyalty program")
else:
  print("Reject Null Hypothesis, i.e, on an average the customers are spending more than 120$ per week, hence the shopkeeper may launch the loyalty program")


Reject Null Hypothesis, i.e, on an average the customers are spending more than 120$ per week, hence the shopkeeper may launch the loyalty program


In [ ]:
stats.norm.ppf(1-(alpha/2))

np.float64(1.959963984540054)

# Call center example

In [ ]:
mu=4
sigma=3
n=50
x_bar=float(input("enter the sample mean:"))
alpha=0.05

#H0: mu=4, i.e., the process is normal, no action is needed
#H1: mu!=4, i.e., the process is not normal, immediate action is needed (two-tailed test)
#test: z-test, since n>30 and sigma is known

z_cal=(x_bar-mu)/(sigma/np.sqrt(n))
z_crit=stats.norm.ppf(1-alpha/2)

if np.absolute(z_cal)<=np.absolute(z_crit):
  print("Accept null hypothesis. Hence,The process is normal, no action is needed")
else:
  print("Reject null hypothesis. Hence,the process is not normal, immediate action is needed")

enter the sample mean:2
Reject null hypothesis. Hence,the process is not normal, immediate action is needed


In [ ]:
np.absolute(-3.7)

np.float64(3.7)

#icecream factor problem

In [ ]:
import pandas as pd

In [ ]:
n=9
mu=0.3
alpha=0.05

#H0: mu<=0.3, the disease is not due to icecream factory, no action is needed
#H1: mu>0.3, the disease is due to the icecream factory, shut down immediately(one tailed)

data=[0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418]
stats.ttest_1samp(data,0.3)

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [ ]:
p_val=stats.ttest_1samp(data,0.3)[1]/2

In [ ]:
if p_val<alpha:
  print("Reject Null Hypothesis,the disease is due to the icecream factory, shut down immediately")
else:
  print("Accept null hypothesis,the disease is not due to icecream factory, no action is needed ")

Reject Null Hypothesis,the disease is due to the icecream factory, shut down immediately


# Control and treatment grp problem

In [ ]:
#H0: mu1=mu2, there is no significant difference between control group and the treatment group
#H1: mu1!=mu2, there is a significant diffence between control grp and treatment group(two-tailed test)

control=[91, 87, 99, 77, 88, 91]
treat=[101, 110, 103, 93, 99, 104]

stats.ttest_ind(control,treat)

TtestResult(statistic=np.float64(-3.4456126735364876), pvalue=np.float64(0.006272124350809803), df=np.float64(10.0))

In [ ]:
p_val=stats.ttest_ind(control,treat)[1]

In [ ]:
if p_val<alpha:
  print("Reject Null Hypothesis,there is a significant diffence between control group and treatment group")
else:
  print("Accept null hypothesis,there is no significant difference between control group and the treatment group ")

Reject Null Hypothesis,there is a significant diffence between control group and treatment group


#2 proportion  test

In [ ]:
#H0: P1=P2, i.e., the proportion of state 1 and state 2 student population getting placed immediately after education is same
#(or) there is no significant difference between proportion of state 1 and state 2 population getting job immediately after education

#H1: P1 != P2, i.e., the proportion of state 1 and state 2 student population getting placed immediately after education is different
#(or) there is a significant difference between proportion of state 1 and state 2 population getting job immediately after education

#test: t-test

alpha=0.05
n1=247
p1=0.37
n2=308
p2=0.39

#let us generate random data following binomial distribution for both the states
import numpy as np
pop1=np.random.binomial(1,p1,n1)
pop2=np.random.binomial(1,p2,n2)

In [ ]:
import scipy.stats as st
st.ttest_ind(pop1,pop2)

TtestResult(statistic=np.float64(-0.9128226506643562), pvalue=np.float64(0.36173360188637405), df=np.float64(553.0))

In [ ]:
p_val=st.ttest_ind(pop1,pop2)[1]
if p_val<alpha:
  print("Reject Null Hypothesis,there is a significant diffence between state 1 proportion and state2 proportion")
else:
  print("Accept null hypothesis,there is no significant difference between state 1 proportion and state2 proportion")


Accept null hypothesis,there is no significant difference between state 1 proportion and state2 proportion
